# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.dev1+g8d84c97.d20230204"
__version_tuple__ = version_tuple = (0, 1, "dev1", "g8d84c97.d20230204")
